### PR TITLE
merge conflicts on isis repaint

### PR DESCRIPTION
**Pull request by zero-24**
fixes merge conflicts an resync to 3.7.x for joomla#11832

### CODE REVIEW

**Comment by ciar4n** [comment]
Thank you @zero-24 

Firstly to say I am a bit of a novice at git would be an understatement :/ 

I tried...

`git checkout -b zero-24-11832 isis-repaint`
`git pull https://github.com/zero-24/joomla-cms.git 11832`

However this throws conflicts with files I would not have changed with the PR. Have I done something wrong? Really sorry about the novice questioning.

**Comment by zero-24** [comment]
You need to fix the merge conflicts against the 3.7.x branch.

**Comment by ciar4n** [comment]
Thank you @zero-24 . Merging branch '3.7.x' into isis-repaint showed up no conflicts. I'm sure I'll figure it out eventually but if there is any obvious reasons for this I'm all ears :)

**Comment by zero-24** [comment]
hmm looks like there are still merge conflicts: 
image

**Comment by ciar4n** [comment]
Yes... just not seeing the conflicts locally...

```
c:\xampp\htdocs\joomla-cms>git merge 3.7.x
Already up-to-date.

c:\xampp\htdocs\joomla-cms>git status
On branch isis-repaint
Your branch is up-to-date with 'origin/isis-repaint'.
nothing to commit, working directory clean
```

**Comment by zero-24** [comment]
Please try to pull the last 3.7.x branch ;) I can have a look later.

**Comment by ciar4n** [comment]
Yep been trying all that.. everything up to date and still the same result...

```
c:\xampp\htdocs\joomla-cms>git checkout 3.7.x
Switched to branch '3.7.x'
Your branch is up-to-date with 'origin/3.7.x'.

c:\xampp\htdocs\joomla-cms>git pull
Already up-to-date.

c:\xampp\htdocs\joomla-cms>git checkout isis-repaint
Switched to branch 'isis-repaint'
Your branch is up-to-date with 'origin/isis-repaint'.

c:\xampp\htdocs\joomla-cms>git status
On branch isis-repaint
Your branch is up-to-date with 'origin/isis-repaint'.
nothing to commit, working directory clean

c:\xampp\htdocs\joomla-cms>git merge 3.7.x
Already up-to-date.
```

**Comment by zero-24** [comment]
hmm can you please review: https://github.com/joomla/joomla-cms/compare/3.7.x...zero-24:11832?expand=1 if this is ok i can send it against the CMS (or you if you want ;) so we have something to merge. it looks like something is broken in your branch :(

**Comment by ciar4n** [comment]
Thank you @zero-24 Yes that is looking good. Should I close #11832 in favor of your PR? Probably best leave the PR in your capable hands ;)

**Comment by zero-24** [comment]
Done: https://github.com/joomla/joomla-cms/pull/12319

Please try to just merge this one: https://github.com/ciar4n/joomla-cms/pull/1 to fix the other PR (installation) so we can get them into 3.7 :+1:

**Pull request closed without merging**
