### PR TITLE
merge conflicts on the install repaint

### PR DESCRIPTION
**Pull request by zero-24**
fixes merge conflicts an resync to 3.7.x for https://github.com/joomla/joomla-cms/pull/11917

### CODE REVIEW

**Comment by zero-24** [comment]
FYI: you need to fix your PR against the 3.7.x branch.

**Comment by zero-24** [comment]
@ciar4n can you check this one for the install PR?

**Comment by ciar4n** [comment]
@zero-24 Will look in to it now

**Comment by zero-24** [comment]
Done see: https://github.com/joomla/joomla-cms/pull/12342 Thanks!

**Comment by ciar4n** [comment]
Ah figured out what I was doing wrong. A simple Git error where I hadn't recently updated my fork of Joomla. Lesson learned! Thanks again @zero-24

**Comment by zero-24** [comment]
No Problem. You have did something great with CSS and I helped you with the git stuff -> teamwork :+1:

**Pull request closed without merging**
